# Generated by Django 3.2.14 on 2022-07-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttype',
            name='number_of_assignments',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
