# Generated by Django 3.2.14 on 2022-07-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundays', '0002_auto_20220722_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
