# Generated by Django 3.2.14 on 2022-07-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundays', '0004_assignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ass_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
